### ISSUE TITLE
Problem setting up Anaconda environment on ARM64 ( Apple Silicon) (zsh shell)

### ISSUE THREAD

**Issue by rollynoel** [thousandbrainsproject/tbp.monty#81]
### Describe the bug

(base) rolly@Rolands-Mac-mini tbp.monty % conda env create --file environment_arm64.yml
/opt/anaconda3/lib/python3.12/argparse.py:2006: FutureWarning: `remote_definition` is deprecated and will be removed in 25.9. Use `conda env create --file=URL` instead.
  action(self, namespace, argument_values, option_string)
Channels:
 - aihabitat
 - pytorch
 - pyg
 - defaults
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed
Channels:
 - aihabitat
 - pytorch
 - pyg
 - defaults
 - conda-forge
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested aihabitat::habitat-sim =0.2.2*
  - nothing provides requested mkl <2022
  - nothing provides blas * mkl needed by pytorch-1.11.0.arm64-py3.8_0

Could not solve for environment specs
The following packages are incompatible
├─ habitat-sim 0.2.2*  does not exist (perhaps a typo or a missing channel);
├─ mkl <2022  does not exist (perhaps a typo or a missing channel);
└─ pytorch 1.11.0*  is not installable because it requires
   └─ blas * mkl, which does not exist (perhaps a missing channel).

**Comment by tristanls** [comment]
Hi @rollynoel, thank you for reporting this. I'm sorry that the installation is failing.

To help reproduce the problem, what is the output if you run `conda info`?

**Comment by rollynoel** [comment]
(base) rolly@Rolands-Mac-mini tbp % conda info

     active environment : base
    active env location : /opt/anaconda3
            shell level : 1
       user config file : /Users/rolly/.condarc
 populated config files : /opt/anaconda3/.condarc
          conda version : 24.9.2
    conda-build version : 24.9.0
         python version : 3.12.7.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=24.9.2=0
                          __osx=15.1.1=0
                          __unix=0=0
       base environment : /opt/anaconda3  (writable)
      conda av data dir : /opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda3/pkgs
                          /Users/rolly/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /Users/rolly/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.9.2 requests/2.32.3 CPython/3.12.7 Darwin/24.1.0 OSX/15.1.1 solver/libmamba conda-libmamba-solver/24.9.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.
                UID:GID : 501:20
             netrc file : None
           offline mode : False

**Comment by tristanls** [comment]
Thank you @rollynoel.

I installed the same version of Anaconda you have and could reproduce the error you ran into.

Please try using these instructions instead and see if these work:
```
conda env create -f environment_arm64.yml --subdir=osx-64
conda init zsh
conda activate tbp.monty
conda config --env --set subdir osx-64
```

**Comment by tristanls** [comment]
@nielsleadholm, you mentioned that you had the full Anaconda installed and that the `--subdir=osx-64` flag wasn’t required. Do you know if the `--subdir=osx-64` is still unnecessary on your machine?

**Comment by rollynoel** [comment]
(base) rolly@MiniMe tbp.monty % conda env create -f environment_arm64.yml --subdir=osx-64
conda init zsh
conda activate tbp.monty
conda config --env --set subdir osx-64
/opt/anaconda3/lib/python3.12/argparse.py:2006: FutureWarning: `remote_definition` is deprecated and will be removed in 25.9. Use `conda env create --file=URL` instead.
  action(self, namespace, argument_values, option_string)
Retrieving notices: ...working... done
Channels:
 - aihabitat
 - pytorch
 - pyg
 - defaults
 - conda-forge
Platform: osx-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:
                                                                                                                                                                                        
Preparing transaction: done                                                                                                                                                             
Verifying transaction: done                                                                                                                                                             
Executing transaction: done                                                                                                                                                             
Installing pip dependencies: - Ran pip subprocess with arguments:                                                                                                                       
['/opt/anaconda3/envs/tbp.monty/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Users/rolly/tbp/tbp.monty/condaenv.73a4k2qk.requirements.txt', '--exists-action=b']                  
Pip subprocess output:                                                                                                                                                                  
                                                                                                                                                                                        
Pip subprocess error:                                                                                                                                                                   
/opt/anaconda3/envs/tbp.monty/.tmpa9kqguj4: line 3: /opt/anaconda3/envs/tbp.monty/bin/python: Bad CPU type in executable                                                                
                                                                                                                                                                                        
failed                                                                                                                                                                                  
                                                                                                                                                                                        
CondaEnvException: Pip failed                                                                                                                                                           
                                                                                                                                                                                        
no change     /opt/anaconda3/condabin/conda                                                                                                                                             
no change     /opt/anaconda3/bin/conda                                                                                                                                                  
no change     /opt/anaconda3/bin/conda-env                                                                                                                                              
no change     /opt/anaconda3/bin/activate                                                                                                                                               
no change     /opt/anaconda3/bin/deactivate                                                                                                                                             
no change     /opt/anaconda3/etc/profile.d/conda.sh                                                                                                                                     
no change     /opt/anaconda3/etc/fish/conf.d/conda.fish                                                                                                                                 
no change     /opt/anaconda3/shell/condabin/Conda.psm1                                                                                                                                  
no change     /opt/anaconda3/shell/condabin/conda-hook.ps1                                                                                                                              
no change     /opt/anaconda3/lib/python3.12/site-packages/xontrib/conda.xsh                                                                                                             
no change     /opt/anaconda3/etc/profile.d/conda.csh                                                                                                                                    
no change     /Users/rolly/.zshrc                                                                                                                                                       
No action taken.

**Comment by tristanls** [comment]
One possible cause of "Bad CPU type in executable" is running the commands from a shell other than `zsh`, which can be verified by inspecting the output of `echo $SHELL`.

However, assuming you are already running `zsh`, the next option may be to see if your Mac has [Rosetta](https://support.apple.com/en-us/102527) installed. The `--subdir=osx-64` is installing Intel binaries. Without Rosetta, your Mac will not be able to emulate Intel instructions.

**Comment by tristanls** [comment]
I'm sorry @rollynoel, I linked to an unhelpful Rosetta installation page. The install instructions apparently are:
```
softwareupdate --install-rosetta
```

**Comment by rollynoel** [comment]
Sounded pretty good, but pytest is a command not found(tbp.monty) rolly@MiniMe tbp.monty % conda env create -f environment_arm64.yml --subdir=osx-64
conda init zsh
conda activate tbp.monty
conda config --env --set subdir osx-64
/opt/anaconda3/lib/python3.12/argparse.py:2006: FutureWarning: `remote_definition` is deprecated and will be removed in 25.9. Use `conda env create --file=URL` instead.
  action(self, namespace, argument_values, option_string)

CondaValueError: prefix already exists: /opt/anaconda3/envs/tbp.monty

no change     /opt/anaconda3/condabin/conda
no change     /opt/anaconda3/bin/conda
no change     /opt/anaconda3/bin/conda-env
no change     /opt/anaconda3/bin/activate
no change     /opt/anaconda3/bin/deactivate
no change     /opt/anaconda3/etc/profile.d/conda.sh
no change     /opt/anaconda3/etc/fish/conf.d/conda.fish
no change     /opt/anaconda3/shell/condabin/Conda.psm1
no change     /opt/anaconda3/shell/condabin/conda-hook.ps1
no change     /opt/anaconda3/lib/python3.12/site-packages/xontrib/conda.xsh
no change     /opt/anaconda3/etc/profile.d/conda.csh
no change     /Users/rolly/.zshrc
No action taken.
(tbp.monty) rolly@MiniMe tbp.monty % pytest
zsh: command not found: pytest

**Comment by nielsleadholm** [comment]
@tristanls yes I run without `--subdir=osx-64` and it installs successfully, i.e. just `conda env create -f environment_arm64.yml`

The below is what I get for `conda info`

```
     active environment : base
    active env location : /Users/nleadholm/anaconda3
            shell level : 1
       user config file : /Users/nleadholm/.condarc
 populated config files : 
          conda version : 4.12.0
    conda-build version : 3.21.8
         python version : 3.9.12.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/nleadholm/anaconda3  (writable)
      conda av data dir : /Users/nleadholm/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/nleadholm/anaconda3/pkgs
                          /Users/nleadholm/.conda/pkgs
       envs directories : /Users/nleadholm/anaconda3/envs
                          /Users/nleadholm/.conda/envs
               platform : osx-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Darwin/24.1.0 OSX/10.16
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

**Comment by rollynoel** [comment]
How do I run the unit tests - pytest gives me "zsh: command not found"

**Comment by rollynoel** [comment]
I removed, re-created & got "... == 318 passed, 498 warnings in 250.87s (0:04:10) ==". Thanks you sir for all your help!

**Comment by tristanls** [comment]
@rollynoel, I'm glad to hear that it's working. Thank you for confirming, and I'm sorry for the trouble.

I'm still confused about why the full Anaconda instructions did not work as written. I'm curious if it was the absence of Rosetta.

If you're up for it, it would be great to see now that you have Rosetta installed if the previous instructions work.

If it is not too much trouble if you were to remove `tbp.monty`:
```
conda env remove --name tbp.monty -y
```
and then install with:
```
conda env create -f environment_arm64.yml
conda init zsh
conda activate tbp.monty
```
does it work now, or does it fail as you reported initially?

(if you do the above and it does not work, to recover back to where it is working would be):
```
conda env remove --name tbp.monty -y
conda env create -f environment_arm64.yml --subdir=osx-64
conda init zsh
conda activate tbp.monty
conda config --env --set subdir osx-64
```

**Comment by rollynoel** [comment]
No, back to:Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides requested aihabitat::habitat-sim =0.2.2*
  - nothing provides requested mkl <2022
  - nothing provides blas * mkl needed by pytorch-1.11.0.arm64-py3.8_0

Could not solve for environment specs
The following packages are incompatible
├─ habitat-sim 0.2.2*  does not exist (perhaps a typo or a missing channel);
├─ mkl <2022  does not exist (perhaps a typo or a missing channel);
└─ pytorch 1.11.0*  is not installable because it requires
   └─ blas * mkl, which does not exist (perhaps a missing channel).

no change     /opt/anaconda3/condabin/conda
no change     /opt/anaconda3/bin/conda
no change     /opt/anaconda3/bin/conda-env
no change     /opt/anaconda3/bin/activate
no change     /opt/anaconda3/bin/deactivate
no change     /opt/anaconda3/etc/profile.d/conda.sh
no change     /opt/anaconda3/etc/fish/conf.d/conda.fish
no change     /opt/anaconda3/shell/condabin/Conda.psm1
no change     /opt/anaconda3/shell/condabin/conda-hook.ps1
no change     /opt/anaconda3/lib/python3.12/site-packages/xontrib/conda.xsh
no change     /opt/anaconda3/etc/profile.d/conda.csh
no change     /Users/rolly/.zshrc
No action taken.

EnvironmentNameNotFound: Could not find conda environment: tbp.monty
You can list all discoverable environments with `conda info --envs`.


(base) rolly@MiniMe tbp.monty %

**Comment by tristanls** [comment]
@rollynoel, thank you for trying it out.

I'm going to close this issue as resolved. Please let us know if you run into other issues.

**Comment by rollynoel** [comment]
When I run into other problems following the documentation on MacOS, what is the best way of reporting them? For example:

-Monty Meets World problems
Opening project in Xcode & running it on your device required a whole lot of messing around.
Running Server Script on Mac
“python src/tbp/monty/frameworks/dataset_utils/server.py” didn’t work. Think server.py runs OK from Visual Studio Code
How to take a picture in the iOS app?

- 4.3 Run the Experiment
python benchmarks/run.py -e ycb_experiments
gets "from tbp.monty.frameworks.run_env import setup_env 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'tbp'"

**Comment by tristanls** [comment]
Hi @rollynoel,

You are welcome to create issues in this repository or start discussions on https://thousandbrains.discourse.group/. We keep an eye on both.
